apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: lagadglav/api:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_DATABASE
              value: metro
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: example
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
