version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: metro
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_DATABASE=metro
      - DB_USER=root
      - DB_PASSWORD=example
    depends_on:
      - db

volumes:
  db_data:

